config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    passwords: 'passwords',
    registrations: 'registrations',
    invitations: 'invitations',
    sessions: 'sessions'
  }

  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # mount ActionCable.server => '/cable'

  resources :university do
    resources :faculty
    collection do
      get :valid_token
      get :search
    end

    member do
      get :prospective_student
      patch :filter_student
      get :application
    end

    member do
      patch :activate
      patch :add_criteria
      get :reload
    end
  end

  resources :course do
    member do
      get :detail
    end

    resources :unit do
      collection do
        get :course_units
        get :search
      end
    end
  end

  resources :application_progress do
    member do
      patch :transition
    end
  end


  resources :student do
    member do
      patch :add_academic
      get :reload
      get :recommendation
      get :application
      patch :filter_application
    end
  end

  resources :courses_unit, only: [:create, :destroy]
  resources :uni_admin
  resources :users_invitations do
    collection do
      get :valid_token
    end

    member do
      put :accept_invitation
    end
  end

  resources :search_engine do
    collection do
      get :search_unit
      get :item_detail
    end
  end


  resources :users do
    collection do
      get :students
      get :universities
      get :student_details
    end
    member do
      post :invite
    end
  end

  resource :subjects
  resources :chats do
    collection do
      get :application
    end
  end

  mount ActionCable.server => '/cable'

  resources :paypals do
    collection do
      post :start_payment
      get :verify_payment
    end
  end

  get 'paypal_confirm', to: 'paypals#verify_payment'

end

app/models/profile.rb
class Profile < ApplicationRecord
  validates_presence_of :firstname, :middlename, :lastname

  has_attached_file :avatar,
                    {
                        url: "/uploads/attachments/:basename.:extension",
                        path: ":rails_root/public/uploads/attachments/:basename.:extension"
                    }

  validates_attachment_size :avatar, less_than: 5.megabytes
  validates_attachment :avatar,
                       :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png", "image/jpg", "image/tiff", "image/bmp"] }

  enum gender: { Male: 4241, Female: 4242, Unknown: 0 }
  belongs_to :user, inverse_of: :profile
end

app/models/user.rb
class User < ApplicationRecord
  include Tokenizable
  include Profileable
  include CourseLooker
  include Recommendation
  include WeightageCalculator
  include ProspectiveStudentHelper

  validates_presence_of :email, :password, on: :create
  devise :invitable, :database_authenticatable, :registerable, :lockable,
    :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  validates_uniqueness_of :email
  validate :password_strength

  has_one :profile, inverse_of: :user, dependent: :destroy
  belongs_to :university, inverse_of: :users, optional: true
  belongs_to :faculty, inverse_of: :users, optional: true
  has_one :address, as: :addressable, dependent: :destroy
  has_many :english_competencies, as: :competenciable, dependent: :destroy
  has_one :highest_english_competency, as: :competenciable, class_name: 'EnglishCompetency'
  has_many :qualifications, inverse_of: :user, dependent: :destroy
  has_many :subjects, through: :qualifications
  has_many :experiences, inverse_of: :user, dependent: :destroy
  has_one :wallet, as: :payee, dependent: :destroy
  has_many :paypal_carts, inverse_of: :user, dependent: :destroy
  has_one  :highest_qualification, :class_name=> "Qualification"
  has_many :chats, inverse_of: :user
  has_many :category_preferances, inverse_of: :user
  has_many :course_categories, through: :category_preferances
  has_many :courses, through: :course_categories
  has_many :application_progresses, inverse_of: :user
  has_one :membership, as: :memberable, dependent: :destroy
  accepts_nested_attributes_for :profile, allow_destroy: true
  accepts_nested_attributes_for :address, allow_destroy: true
  accepts_nested_attributes_for :english_competencies, allow_destroy: true
  accepts_nested_attributes_for :qualifications, allow_destroy: true
  accepts_nested_attributes_for :experiences, allow_destroy: true

  enum user_type: {portal_admin: 0, uni_admin: 1, student: 2}
  enum recent_qualification: { high_school: 0, diploma: 1, graduate: 2, post_graduate: 3, phd: 4, other: 5}

  after_create :send_invitation

  delegate :name, to: :university, prefix: true, allow_nil: :true
  delegate :salutation, :firstname, :lastname, to: :profile, allow_nil: :false
  delegate :country, to: :address, prefix: false, allow_nil: :true

  paginates_per 10

  def pic
    profile&.avatar&.url || '/default_photo/photo.png'
  end

  def name
    full_name = "#{profile&.firstname} #{profile&.middlename} #{profile&.lastname}"
    full_name.blank? ? email : full_name
  end

  def send_invitation
    self.invite!
  end

  def highest_qualification_id
    highest_qualification&.id
  end

  private

  def password_strength
    if password && !(password.match(/(?=.*\d)(?=.*[A-Z])/))
      errors.add(:password, I18n.t('devise.passwords.invalid_password'))
    end
  end
end

app/controllers/users/invitations_controller.rb
# class Users::InvitationsController < Devise::InvitationsController
#   private
#
#   # this is called when creating invitation
#   # should return an instance of subject class
#   def invite_resource
#     binding.pry
#     # skip sending emails on invite
#     super { |user| user.skip_invitation = true }
#   end
#
#   # this is called when accepting invitation
#   # should return an instance of subject class
#   def accept_resource
#     binding.pry
#     subject = resource_class.accept_invitation!(update_resource_params)
#     # Report accepting invitation to analytics
#     Analytics.report('invite.accept', subject.id)
#     subject
#   end
#
#   def new
#     binding.pry
#   end
#
#   def create
#     binding.pry
#   end
#
#   def edit
#     binding.pry
#   end
#
#   def update
#     binding.pry
#   end
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i|show students universities|

  def show
    if  current_user.portal_admin?
      @universities = University.all
      @students = User.student.all
    elsif current_user.student?
      current_user.english_competencies.build if current_user.english_competencies.empty?
      current_user.qualifications.build if current_user.qualifications.empty?
      current_user.build_wallet if current_user.wallet.nil?
      current_user.build_address if current_user.address.nil?
    else
      @university = current_user.university
    end
  end

  def students
    @users = User.student.map{|u| u.calc_weightage(current_user.university)}
  end

  def universities
    @universities = University.all
  end

  def student_details
    @student = User.find_by(id: params[:student_id])
  end

  def search
    @results = {
      universities: University.search(params["term"]),
      courses: Course.search(params["term"]),
      units: Unit.search(params["term"])
    }
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "User details updated successfully"
    else
      flash[:error] = @user.errors.messages
    end
  end

  def invite
    User.new(user_params).save
    flash[:success] = 'User invited successfully'
    render :show, type: 'proile'
  end

  private

  def user_params
    params
      .require(:user)
      .permit(:email, :password, profile_attributes:[:firstname, :middlename, :lastname, :mobile_no])
  end
end

app/views/users/profiles/_portal_admin.html.erb
<div class="col-lg-3">
  <%= render(partial: "home/portal_admin_nav") %>
</div>

<div class="col-lg-9">
  <% if params[:type].eql? 'students' %>
    <%= render(partial: "users/profiles/students") %>
  <%else%>
    <%= render(partial: "users/profiles/universities") %>
  <%end %>
</div>

app/views/users/profiles/_portfolio.html.erb
<div class="col-lg-9">
  <%= form_for @user, url: {controller: :student, action: :update, method: :put} do |f| %>
    <div class="line">
      English Competency
    </div><br><br><br><br><br>

    <%= f.fields_for :english_competencies do |g| %>
      <%= label_tag(:competency_type, "Type:", class: 'labelLarge') %>
      <%= g.select :competency_type, ["IELTS", "PTE"] %><br><br>

      <%= label_tag(:expiry, "Expiry:", class: 'labelLarge') %>
      <%= g.date_field :expiry, class: 'mediumInput' %><br><br>

      <%= label_tag(:overall_band, "Overall Band:", class: 'labelLarge') %>
      <%= g.text_field :overall_band, class: 'mediumInput' %><br><br>

      <%= label_tag(:speaking, "Speaking:", class: 'labelLarge') %>
      <%= g.text_field :speaking, class: 'smallInput' %><br><br>

      <%= label_tag(:writing, "Writing:", class: 'labelLarge') %>
      <%= g.text_field :writing, class: 'mediumInput' %><br><br>

      <%= label_tag(:reading, "Reading:", class: 'labelLarge') %>
      <%= g.text_field :reading, class: 'mediumInput' %><br><br>

      <%= label_tag(:listening, "Listening:", class: 'labelLarge') %>
      <%= g.text_field :listening, class: 'mediumInput' %><br><br>
    <% end %>

    <div class="line">
      Highest Qualification
    </div><br><br><br><br><br>

    <%= f.fields_for :qualifications do |g| %>
      <%= label_tag(:highest_qualification, "Qualification:", class: 'labelLarge') %>
      <%= g.select :highest_qualification, [["PHD", "phd"], ["Post Graduate", "post_graduate"], ["Under Graduate",
        "graduate"], ["Diploma", "diploma"],
        ["Certificate Or High School", "high_school"]], class: 'mediumInput' %><br><br>

      <%= label_tag(:course, "Course:", class: 'labelLarge') %>
      <%= g.text_field :course, class: 'mediumInput' %><br><br>

      <%= label_tag(:overall_percentage, "Percentage:", class: 'labelLarge') %>
      <%= g.text_field :overall_percentage, class: 'mediumInput' %><br><br>

      <%= g.text_field :subject, readonly: 'readonly' %>

      <%= label_tag(:subject, "Subject:", class: 'labelLarge') %>
      <input type="text" class="mediumInput">
      <%= label_tag(:score, "Score:", class: 'labelSmall') %>
      <input type="text" class="smallInput"><br>


      <%= label_tag(:completed_year, "Completed Year:", class: 'labelLarge') %>
      <%= g.date_field :completed_year, class: 'mediumInput' %><br><br>
    <% end %>

    <div class="line">
      Experiences
    </div><br><br><br><br><br>

    <%= f.fields_for :experiences do |g| %>
      <%= label_tag(:job_type, "Job Name:", class: 'labelLarge') %>
      <%= g.text_field :job_type, class: 'mediumInput' %><br><br>

      <%= label_tag(:start, "Start Date:", class: 'labelLarge') %>
      <%= g.date_field :start, class: 'mediumInput' %><br><br>

      <%= label_tag(:end, "End Date:", class: 'labelLarge') %>
      <%= g.date_field :end, class: 'mediumInput' %><br><br>

      <%= label_tag(:company, "Company Name:", class: 'labelLarge') %>
      <%= g.text_field :company, class: 'mediumInput' %><br><br>

      <%= label_tag(:responsibility, "Responsibility:", class: 'labelLarge') %>
      <%= g.text_field :responsibility, class: 'mediumInput' %><br><br>
    <% end %>

    <%= label_tag(:submit, "", class: 'labelLarge') %>
    <%= f.submit 'Update', class: 'largeSubmit' %>
  <% end %>
</div>

app/views/users/profiles/_search.html.erb
<!--<!DOCTYPE html>-->
<!--<html>-->
<!--<head>-->
<!--  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
<!--  <style>-->
<!--    * {box-sizing: border-box;}-->

<!--    body {-->
<!--      margin: 0;-->
<!--      font-family: Arial, Helvetica, sans-serif;-->
<!--    }-->

<!--    .topnav {-->
<!--      overflow: hidden;-->
<!--      background-color: #e9e9e9;-->
<!--    }-->

<!--    .topnav a {-->
<!--      float: left;-->
<!--      display: block;-->
<!--      color: black;-->
<!--      text-align: center;-->
<!--      padding: 14px 16px;-->
<!--      text-decoration: none;-->
<!--      font-size: 17px;-->
<!--    }-->

<!--    .topnav a:hover {-->
<!--      background-color: #ddd;-->
<!--      color: black;-->
<!--    }-->

<!--    .topnav a.active {-->
<!--      background-color: #2196F3;-->
<!--      color: white;-->
<!--    }-->

<!--    .topnav .search-container {-->
<!--      float: right;-->
<!--    }-->

<!--    .topnav input[type=text] {-->
<!--      padding: 6px;-->
<!--      margin-top: 8px;-->
<!--      font-size: 17px;-->
<!--      border: none;-->
<!--    }-->

<!--    .topnav .search-container button {-->
<!--      float: right;-->
<!--      padding: 6px 10px;-->
<!--      margin-top: 8px;-->
<!--      margin-right: 16px;-->
<!--      background: #ddd;-->
<!--      font-size: 17px;-->
<!--      border: none;-->
<!--      cursor: pointer;-->
<!--    }-->

<!--    .topnav .search-container button:hover {-->
<!--      background: #ccc;-->
<!--    }-->

<!--    @media screen and (max-width: 600px) {-->
<!--      .topnav .search-container {-->
<!--        float: none;-->
<!--      }-->
<!--      .topnav a, .topnav input[type=text], .topnav .search-container button {-->
<!--        float: none;-->
<!--        display: block;-->
<!--        text-align: left;-->
<!--        width: 100%;-->
<!--        margin: 0;-->
<!--        padding: 14px;-->
<!--      }-->
<!--      .topnav input[type=text] {-->
<!--        border: 1px solid #ccc;-->
<!--      }-->
<!--    }-->
<!--  </style>-->
<!--</head>-->
<!--<body>-->

<!--<div class="topnav">-->
<!--  <a class="active" href="#home">Home</a>-->
<!--  <a href="#about">About</a>-->
<!--  <a href="#contact">Contact</a>-->
<!--  <div class="search-container">-->
<!--    <form action="/action_page.php">-->
<!--      <input type="text" placeholder="Search.." name="search">-->
<!--      <button type="submit"><i class="fa fa-search"></i></button>-->
<!--    </form>-->
<!--  </div>-->
<!--</div>-->

<!--<div style="padding-left:16px">-->
<!--  <h2>Responsive Search Bar</h2>-->
<!--  <p>Navigation bar with a search box and a submit button inside of it.</p>-->
<!--  <p>Resize the browser window to see the responsive effect.</p>-->
<!--</div>-->

<!--</body>-->
<!--</html>-->

app/views/users/profiles/_student_academic_english.html.erb
<div class="line">
  <p style="color: darkorange; font-size: 20px;">Add English Competency</p>
</div><br><br>

<%= form_for current_user, url: {controller: :student, action: :add_academic, method: :patch, id: current_user.id} do |f| %>
  <%= f.fields_for current_user.english_competencies.new do |g| %>
    <%= hidden_field(:type, value='english') %>
    <%= label_tag(:competency_type, "Type:", class: 'labelLarge') %>
    <%= g.select_tag(:criteria, options_for_select(["IELTS", "PTE" ], "IELTS"), class: 'borderlessInputMedium') %>

    <%= label_tag(:expiry, "Expiry:", class: 'labelLarge') %>
    <%= g.date_field :expiry, class: 'borderlessInputMedium' %><br><br>

    <%= label_tag(:overall_band, "Overall Band:", class: 'labelLarge') %>
    <%= g.number_field :overall_band, step: :any, class: 'borderlessInputMedium' %>

    <%= label_tag(:speaking, "Speaking:", class: 'labelLarge') %>
    <%= g.number_field :speaking,  step: :any, class: 'borderlessInputMedium' %><br><br>

    <%= label_tag(:writing, "Writing:", class: 'labelLarge') %>
    <%= g.number_field :writing,  step: :any, class: 'borderlessInputMedium' %>

    <%= label_tag(:reading, "Reading:", class: 'labelLarge') %>
    <%= g.number_field :reading, step: :any, class: 'borderlessInputMedium' %><br><br>

    <%= label_tag(:listening, "Listening:", class: 'labelLarge') %>
    <%= g.number_field :listening, step: :any, class: 'borderlessInputMedium' %>

    <%= g.fields_for :attachments_attributes do |g| %>
        <%= g.hidden_field(:name, value: 'English Competency') %>
        <%= g.file_field :file %>
      <% end %>
  <% end %>
  <%= label_tag(:submit, "", class: 'labelLarge') %>
  <%= f.submit 'Add', class: 'mediumSubmit' %>
<% end %><br>

<table class="table", style="width: 100%;">
  <tr style="height: 50px; background-color: #ddd;">
    <th>Type</th><th>Expiry</th><th>Overall
    Bank</th><th>Speaking</th><th>Writing</th><th>Reading</th><th>Listening</th><th>File</th><th>Action</th>
  </tr>
  <% current_user.english_competencies.select(&:persisted?).each do |g| %>
    <tr>
      <th><%= g.competency_type %></th>
      <td><%= g.expiry %></td>
      <td><%= g.overall_band %></td>
      <td><%= g.speaking %></td>
      <td><%= g.writing %></td>
      <td><%= g.reading %></td>
      <td><%= g.listening %></td>
      <td><%= link_to("download", g.attachments.first.file(:original, false),
        download: g.attachments.first.name, :style => "color: blue") unless g.attachments.first.nil? %></td>
      <td><a style="color: red;" href="<%= root_url %>/student/<%= current_user.id %>/reload?destroy=true&type=english&type_id=<%= g.id %>">delete</a></td>
    </tr>
  <% end%>
</table>

app/views/users/profiles/_student_academic_nav.html.erb
<script>
  document.getElementById('stud_third').classList.add("active");
</script>

<h1 style="color: red">Academic Scores</h1>

<div class="tab">
  <button class="tablinks" id="english_tab" onclick="openAcademic(event, 'english')">English Competency</button>
  <button class="tablinks" id="qualification_tab" onclick="openAcademic(event, 'academic')">Academic Scores</button>
  <button class="tablinks" id="experience_tab" onclick="openAcademic(event, 'experience')">Experiences</button>
  <button class="tablinks" id="preference_tab" onclick="openAcademic(event, 'preference')">Preference</button>
</div>

<div id="english" class="tabcontent">
  <%= render(partial: "users/profiles/student_academic_english") %>
</div>

<div id="academic" class="tabcontent">
  <%= render(partial: "users/profiles/student_academic_qualification") %>
</div>

<div id="experience" class="tabcontent">
  <%= render(partial: "users/profiles/student_academic_experience") %>
</div>

<div id="preference" class="tabcontent">
  <%= render(partial: "users/profiles/student_academic_preference") %>
</div>


 <script>
    function openAcademic(evt, academicName) {
      var i, tabcontent, tablinks;
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
      }
      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      document.getElementById(academicName).style.display = "block";
      evt.currentTarget.className += " active";
    }

    var tabsName = "<%= tabName %>" != null ? "<%= tabName %>" : "english_tab";
    document.getElementById(tabsName).click();
  </script>
</div>

app/views/users/profiles/_student_academic_preference.html.erb
<div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</div>

<div class="line">
  <p style="color: darkorange; font-size: 20px;">Set Your Career Goals and Budget Limit</p>
</div><br><br>

<div>
  <%= form_for current_user, url: {controller: :student, action: :add_academic, method: :patch, id: current_user.id} do
  |f| %>

    <%= f.fields_for current_user.category_preferances.new  do |g| %>
      <%= hidden_field(:type, value='preferance') %>

      <%= label_tag(:course_category, "Category:", class: 'labelExtraLarge') %>
      <%= select_tag(:course_category_id, options_from_collection_for_select(CourseCategory.all, "id", "name"), class:
        'borderlessInputLarge') %><br><br>

      <%= label_tag(:fees, "Affordable fees:", class: 'labelExtraLarge') %>
      <%= number_field_tag(:fees, nil, step: :any, class: 'borderlessInputLarge') %><br><br>
    <% end %>

    <%= label_tag(:submit, "", class: 'labelLarge') %>
    <%= f.submit 'Add', class: 'mediumSubmit' %>
  <% end %><br>

  <table class="table", style="width: 100%;">
    <tr style="height: 50px; background-color: #ddd;">
      <th>Category</th><th>Affordable fees</th><th>Description</th><th>Action</th>
    </tr>
    <% current_user.category_preferances.select(&:persisted?).each do |g| %>
      <tr>
        <th><%= g.course_category.name %></th>
        <td><%= g.fees %></td>
        <td><%= g.course_category.description %></td>
        <td><a style="color: red;" href="<%= root_url %>/student/<%= current_user.id
        %>/reload?destroy=true&type=category&type_id=<%=
          g.id %>">delete</a></td>
      </tr>
    <% end%>
  </table>
</div>

app/views/users/profiles/_student_academic_subject_modal.html.erb
<div>
<!--  <meta charset="utf-8">-->
<!--  <meta name="viewport" content="width=device-width, initial-scale=1">-->
<!--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</div>

<div class="container" style="width: 100px;">
  <!-- Trigger the modal with a button -->
  <label data-toggle="modal" data-target="#myModal" id="modalOpener"><%= qualification.subjects.count %></label>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Subject Details</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>

        </div>
        <div class="modal-body">
          <div>
            <%= form_for qualification.subjects.new, url: {controller: :subjects, action: :create, method: :post} do
            |f| %>
              <%= f.hidden_field :subjectable_id, value: qualification.id %>
              <%= f.hidden_field(:subjectable_type, value: 'Qualification') %>
              <%= f.text_field :name, class: 'mediumInput', placeholder: "Subject name"%>
              <%= f.text_field :percentage, class: 'mediumInput', placeholder: "Percentage"%><br><br>
              <%= f.text_area :description, class: 'extraLargeInput', placeholder: "Description"%><br><br>
              <%= f.submit 'Submit', class: 'mediumSubmit'%><br><br>
            <%end%>
          </div>

          <table class="table", style="width: 100%;">
            <tr style="height: 50px; background-color: #ddd;">
            <th>Name</th><th>Score</th><th>Description</th><th>Action</th>
            </tr>
            <% qualification.subjects.select(&:persisted?).each do |sub| %>
            <tr>
              <th><%= sub.name %></th><td><%= sub.percentage %></td><td><%= sub.description %></td>
              <td><%= link_to "Delete", subjects_path(id: sub.id), method: :delete, :style=> "color: red;", data: {
                confirm: 'Are you sure?'
              }%></td>
            </tr>
          <% end %>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/users/profiles/_student_readonly_subject_model.html.erb
<div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</div>

<div class="container" style="width: 100px;">
  <!-- Trigger the modal with a button -->
  <label data-toggle="modal" data-target="#myModal" id="modalOpener"><%= qualification.subjects.count %></label>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Subject Details</h4>
        </div>

          <table class="table", style="width: 100%;">
            <tr style="height: 50px; background-color: #ddd;">
              <th>Name</th><th>Score</th><th>Description</th>
            </tr>
            <% qualification.subjects.select(&:persisted?).each do |sub| %>
              <tr>
                <th><%= sub.name %></th><td><%= sub.percentage %></td><td><%= sub.description %></td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/users/profiles/_student_search.html.erb
<script>
  document.getElementById('stud_first').classList.add("active");
</script>

<div style="margin-top: 300px; padding-left: 30px;">
  <form method="get" action="<%= root_url %>/search_engine" id="search-form">
    <div class="input-group main-form-inputs search-text">
      <input type="text" name="term" id="term" class="form-control search-text" value="<%= params[:term] %>"
             placeholder="Search preferred universities/courses">
      <span class="input-group-btn">
        <button class="btn btn-default search-btn" type="submit">Search</button>
      </span>
    </div>
  </form>
</div>

app/views/users/profiles/_uni_admin.html.erb
<div class="col-lg-3">
  <%= label_tag :space, "" %>
</div>

<div class="col-lg-9">
  <% if params[:type].eql? 'university' %>
    <%= render(partial: "users/profiles/uni_admin_university_profile") %>
  <%elsif params[:type].eql? 'rule'%>
    <%= render(partial: "users/profiles/uni_admin_selection_criteria_nav", locals: {tabName: 'rule_tab'}) %>
  <%elsif params[:type].eql? 'faculty'%>
    <%= render(partial: "users/profiles/student_recommendation") %>
  <%elsif params[:type].eql? 'students'%>
    <%= render(partial: "users/profiles/student_recommendation") %>
  <%else%>
    <%= render(partial: "users/profiles/uni_admin_profile_nav", locals: {tabName: 'profile_tab'}) %>
  <%end %>
</div>

app/views/users/profiles/_uni_admin_profile.html.erb
<div class="top-space">
  <div class="line">
    Personal Detail
  </div><br><br><br><br><br>

  <%= form_for @user, url: { action: :update, method: :put, id: @user.id} do |f| %>
    <%= label_tag(:email, "Email:", class: 'labelLarge') %>
    <%= f.text_field :email, class: 'largeInput' %><br><br>
    <%= f.fields_for :profile do |g| %>
      <%= label_tag(:firstname, "First Name:", class: 'labelLarge') %>
      <%= g.text_field :firstname, class: 'largeInput' %><br><br>

      <%= label_tag(:middlename, "Middle Name:", class: 'labelLarge') %>
      <%= g.text_field :middlename, class: 'largeInput' %><br><br>

      <%= label_tag(:lastname, "Last Name:", class: 'labelLarge') %>
      <%= g.text_field :lastname, class: 'largeInput' %><br><br>

      <%= label_tag(:mobile_no, "Mobile No:", class: 'labelLarge') %>
      <%= g.text_field :mobile_no, class: 'largeInput' %><br><br>
    <% end %>


    <%= label_tag(:submit, "", class: 'labelLarge') %>
    <%= f.submit 'Update', class: 'largeSubmit' %>
  <% end %>
</div>