config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    passwords: 'passwords',
    registrations: 'registrations',
    invitations: 'invitations',
    sessions: 'sessions'
  }

  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # mount ActionCable.server => '/cable'

  resources :university do
    resources :faculty
    collection do
      get :valid_token
      get :search
    end

    member do
      get :prospective_student
      patch :filter_student
      get :application
    end

    member do
      patch :activate
      patch :add_criteria
      get :reload
    end
  end

  resources :course do
    member do
      get :detail
    end

    resources :unit do
      collection do
        get :course_units
        get :search
      end
    end
  end

  resources :application_progress do
    member do
      patch :transition
    end
  end


  resources :student do
    member do
      patch :add_academic
      get :reload
      get :recommendation
      get :application
      patch :filter_application
    end
  end

  resources :courses_unit, only: [:create, :destroy]
  resources :uni_admin
  resources :users_invitations do
    collection do
      get :valid_token
    end

    member do
      put :accept_invitation
    end
  end

  resources :search_engine do
    collection do
      get :search_unit
      get :item_detail
    end
  end


  resources :users do
    collection do
      get :students
      get :universities
      get :student_details
    end
    member do
      post :invite
    end
  end

  resource :subjects
  resources :chats do
    collection do
      get :application
    end
  end

  mount ActionCable.server => '/cable'

  resources :paypals do
    collection do
      post :start_payment
      get :verify_payment
    end
  end

  get 'paypal_confirm', to: 'paypals#verify_payment'

end

app/models/university.rb
require 'elasticsearch/model'
class University < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  validates_presence_of :name, :weblink

  has_one :focal_contact, inverse_of: :university, dependent: :destroy
  has_one :address, as: :addressable, dependent: :destroy
  has_one :wallet, as: :payee, dependent: :destroy
  has_many :users, inverse_of: :university, dependent: :destroy
  has_many :faculties, inverse_of: :university, dependent: :destroy
  has_many :courses, through: :faculties
  has_many :english_competencies, as: :competenciable, dependent: :destroy
  has_many :academic_eligibilities, as: :eligiable, dependent: :destroy
  has_many :country_criterias, inverse_of: :university, dependent: :destroy
  has_many :criteria_rules, inverse_of: :university, dependent: :destroy
  has_one :experience_criteria, inverse_of: :university, dependent: :destroy
  has_many :qualification_criterias, inverse_of: :university, dependent: :destroy
  has_one :membership, as: :memberable, dependent: :destroy
  has_many :units, inverse_of: :university, dependent: :destroy
  accepts_nested_attributes_for(
  :focal_contact,
    :address,
    :english_competencies,
    :academic_eligibilities,
    allow_destroy: true
  )

  before_create :assign_token
  after_create :notify_portal_admin

  # after_save    { Indexer.perform_async(:index,  self.id) }
  # after_destroy { Indexer.perform_async(:delete, self.id) }

  settings do
    mappings dynamic: false do
      indexes :name, type: :text
      indexes :remark, type: :text
    end
  end

  def search_detail
    "#{name} is locacated at #{address.full_address} and offers #{courses.count} courses at different levels. For
     details please visit the link..."
  end

  def assign_token
    self.token = Devise.token_generator.generate(self.class, :token).second
  end

  def notify_portal_admin
    UniversityMailer.notify_portal_admin(self).deliver_now
  end

  def english_competencies
    return super unless super.empty?
    super.build(
      [{
        competency_type: :IELTS,
        overall_band: 6.5,
        speaking: 6.0,
        writing: 6.0,
        reading: 6.0,
        listening: 6.0
       },
      {
        competency_type: :PTE,
        overall_band: 6.5,
        speaking: 6.0,
        writing: 6.0,
        reading: 6.0,
        listening: 6.0
      }]
    )
  end

  def academic_eligibilities
    return super unless super.empty?
    super.build(
           [
             { eligibility_type: 'Post Graduate', minimum_score: 60, code: 'post_graduate' },
             { eligibility_type: 'Under Graduate', minimum_score: 60, code: 'graduate'},
             { eligibility_type: 'Diploma', minimum_score: 60, code: 'diploma' },
             { eligibility_type: 'Certificate Or High School', minimum_score: 60, code: 'high_school' }
           ]
    )
  end

  def activated?
    return false if wallet.nil?
    wallet.end_date > DateTime.now
  end

  def experience_criteria
    super.nil? ? self.build_experience_criteria : super
  end

  def address
    super || self.build_address
  end

end

app/controllers/university_controller.rb
class UniversityController < ApplicationController
  require 'will_paginate/array'

  def create
    @uni = University.new(uni_params)

    if @uni.save
      flash[:success] = "University created successfully"
    else
      render json: {error: {message: 'Error creating university'}, success: false}, status: :unprocessable_entity
    end
  end

  def show
    @university = University.find(params[:id])
    @user = User.uni_admin.first
  end

  def update
    if university.update_attributes(uni_params)
      flash[:success] = "University details updated successfully"
    else
      flash[:danger] = university.errors.messages
    end
    redirect_to(controller: :users, action: :show, id: current_user.id, params:{type: 'university'})
  end

  def search
    if params[:token].present?
     @uni = University.find_by(token: params[:token])
     @uni.build_wallet if @uni.present? && @uni.wallet.nil?
    end
  end

  def activate
    @activator = UniActivator.new(uni_params)
    if @activator.activate?
      render json: {message: 'University Activated Successfully', success: true}, status: :ok
    else
      render json: {error: {message: 'Error activating university'}, success: false}, status: :unprocessable_entity
    end
  end

  def new
    @uni = University.new
    @focal_contact = @uni.build_focal_contact
    @address = @uni.build_address(street_no: '', suburb: '', post_code: '')
  end

  def add_criteria
    type =  params[:type].keys.first
    form = SelectionCriteriaForm.new(current_user, send(type+'_params'), type, params[:criteria])

    if form.save
      flash[:success] = 'Saved Successfully'
    else
      flash[:danger] = form.errors.messages
    end
  end

  def reload
    if params[:type].eql?('rule')
      criteria = CriteriaRule.find_by(id: params[:type_id])
      criteria.destroy unless criteria.nil?
    elsif params[:type].eql?('english')
      english = EnglishCompetency.find_by(id: params[:type_id])
      english.destroy unless english.nil?
    elsif params[:type].eql?('experience')
      experience = ExperienceCriteria.find_by(id: params[:type_id])
      experience.destroy unless experience.nil?
    elsif params[:type].eql?('qualification')
      qualification = QualificationCriteria.find_by(id: params[:type_id])
      qualification.destroy unless qualification.nil?
    elsif params[:type].eql?('country')
      country = CountryCriteria.find_by(id: params[:type_id])
      country.destroy unless country.nil?
    elsif params[:type].eql?('subject')
      subject = Subject.find_by(id: params[:type_id])
      subject.destroy unless subject.nil?
    end
    flash[:success] = 'Delete Successful'

    if params[:course_id].present?
      redirect_to(controller: :course, action: :show, id: params[:course_id], params:{type: 'english'})
    end
  end

  def prospective_student
    qualification_ids = User.student.map(&:highest_qualification_id).compact
    students = User.student.joins(:qualifications).where('qualifications.id IN (?) AND level = ?',qualification_ids, 4)
    @students = students.paginate(:page=> params[:page], per_page: 4)
  end

  def filter_student
    qualification_ids = User.student.map(&:highest_qualification_id).compact
    students = User.student.joins(:qualifications).where('qualifications.id IN (?) AND level = ?',qualification_ids,
      CONSTANTS[params[:criteria]])

    students = students.select{|u| u.calc_weightage(current_user.university)}
    students = students.sort_by{|m| m.total_weightage}.reverse!
    @students = students.paginate(:page=> params[:page], per_page: 4)
  end

  def application
    @courses = Course.joins(:faculty, :application_progresses).where('faculties.university_id = ?', params[:id]).uniq
                 .paginate(:page=> params[:page], per_page: 2)
  end

  private

  def university
    @university = University.find(params[:id])
  end

  def english_params
    params[:university][:english_competency]
      .permit(:id, :overall_band, :competency_type, :speaking, :listening, :writing, :reading)
  end

  def experience_params
    params[:university][:experience_criteria]
      .permit(:related_experience, :unrelated_experience, :description)
  end

  def qualification_params
    params[:university][:qualification_criteria]
      .permit(:qualification_type, :weightage, :description)
  end

  def rule_params
    params[:university][:criteria_rule].permit(:weightage, :description)
  end

  def country_params
    params[:university][:country_criteria].permit(:country, :weightage, :description)
  end

  def uni_params
    params
      .require(:university)
      .permit(:id, :name, :weblink, :remark, :token, :campus, :semester_living_expenses,
        focal_contact_attributes: [:id, :firstname, :middlename, :lastname, :email, :phone_number],
        english_competencies_attributes: [:id, :overall_band, :expiry, :competency_type, :speaking, :listening, :writing,
          :reading],
        academic_eligibilities_attributes: [:id, :code, :eligibility_type, :minimum_score],
        address_attributes: [:id, :street_no, :street_name, :suburb, :post_code, :city, :country],
        selection_criterias: [:id, :criteria_type, :weightage, :description],
        country_weightages: [:id, :country, :weightage, :description]
      )
  end
end

app/views/university/_criteria.html.erb
<div class="col-lg-9">
  <%= form_for @university, url: {controller: :university, action: :update, method: :put, id: @university.id} do |f| %>
    <div class="line">
      English Competency
    </div><br><br><br><br><br>

    <%= f.fields_for :english_competencies do |g| %>
      <%= label_tag(:competency_type, "Type:", class: 'labelLarge') %>
      <%= g.text_field :competency_type, class: 'smallInput', readonly: "readonly" %><br><br>

      <%= label_tag(:overall_band, "Overall Band:", class: 'labelLarge') %>
      <%= g.text_field :overall_band, class: 'smallInput' %><br><br>

      <%= label_tag(:speaking, "Speaking:", class: 'labelLarge') %>
      <%= g.text_field :speaking, class: 'smallInput' %>

      <%= label_tag(:writing, "Writing:", class: 'labelLarge') %>
      <%= g.text_field :writing, class: 'smallInput' %><br><br>

      <%= label_tag(:reading, "Reading:", class: 'labelLarge') %>
      <%= g.text_field :reading, class: 'smallInput' %>

      <%= label_tag(:listening, "Listening:", class: 'labelLarge') %>
      <%= g.text_field :listening, class: 'smallInput' %><br><br><br><br>
    <% end %>

    <div class="line">
      Academic Eligibility
    </div><br><br><br><br><br>

    <%= f.fields_for :academic_eligibilities do |g| %>
      <%= g.hidden_field :code, class: 'smallInput' %><br><br>

      <%= label_tag(:eligibility_type, "Qualification:", class: 'labelLarge') %>
      <%= g.text_field :eligibility_type, class: 'largeInput', readonly: "readonly" %>

      <%= label_tag(:minimum_score, "Minimum Score:", class: 'labelLarge') %>
      <%= g.text_field :minimum_score, class: 'smallInput' %><br><br>
    <% end %>


    <%= label_tag(:submit, "", class: 'labelLarge') %>
    <%= f.submit 'Update', class: 'largeSubmit' %>
  <% end %>
</div>

app/views/university/_university_profile.html.erb
<div class="top-space">
  <div class="line">
    University Detail
  </div><br><br><br><br><br>
  <%= form_for @university, url: {controller: :university, action: :update, method: :put, id: @university.id} do |f| %>
    <%= label_tag(:uni_name, "University Name:", class: 'labelLarge') %>
    <%= f.text_field :name, class: 'largeInput' %><br><br>

    <%= label_tag(:weblink, "Website Link:", class: 'labelLarge') %>
    <%= f.text_field :weblink, class: 'largeInput' %><br><br>

    <%= label_tag(:campus, "Campus:", class: 'labelLarge') %>
    <%= f.text_field :campus, class: 'largeInput' %><br><br>

    <%= label_tag(:semester_living_expenses, "Living expenses:", class: 'labelLarge') %>
    <%= f.text_area :semester_living_expenses, placeholder: "Uni logde per semester", class: 'largeInput' %><br><br>

    <%= label_tag(:remark, "Remark:", class: 'labelLarge') %>
    <%= f.text_area :remark, class: 'largeInput' %><br><br>

    <div class="line">
      Personal Detail
    </div><br><br><br><br><br>

    <%= f.fields_for :focal_contact do |g| %>
      <%= label_tag(:firstname, "First Name:", class: 'labelLarge') %>
      <%= g.text_field :firstname, class: 'largeInput' %><br><br>

      <%= label_tag(:middlename, "Middle Name:", class: 'labelLarge') %>
      <%= g.text_field :middlename, class: 'largeInput' %><br><br>

      <%= label_tag(:lastname, "Last Name:", class: 'labelLarge') %>
      <%= g.text_field :lastname, class: 'largeInput' %><br><br>

      <%= label_tag(:email, "Email:", class: 'labelLarge') %>
      <%= g.text_field :email, class: 'largeInput' %><br><br>

      <%= label_tag(:phone_no, "Phone No:", class: 'labelLarge') %>
      <%= g.text_field :phone_number, class: 'largeInput' %><br><br>
    <% end %>

    <div class="line">
      Present Address
    </div><br><br><br><br><br>

    <%= f.fields_for :address do |g| %>
      <%= label_tag(:street_no, "Street No:", class: 'labelSmall') %>
      <%= g.text_field :street_no, class: 'smallInput' %>

      <%= label_tag(:street_name, "street Name:", class: 'labelLarge') %>
      <%= g.text_field :street_name, class: 'mediumInput' %><br><br>

      <%= label_tag(:suburb, "Suburb:", class: 'labelSmall') %>
      <%= g.text_field :suburb, class: 'mediumInput' %>

      <%= label_tag(:post_code, "Post Code:", class: 'labelSmall') %>
      <%= g.text_field :post_code, class: 'smallInput' %><br><br>

      <%= label_tag(:city, "City:", class: 'labelSmall') %>
      <%= g.text_field :city, class: 'mediumInput' %><br>

      <%= label_tag(:country, "Country:", class: 'labelSmall') %>
      <%= g.text_field :country, class: 'mediumInput' %><br><br>
    <% end %>

    <%= label_tag(:submit, "", class: 'labelLarge') %>
    <%= f.submit 'Update', class: 'largeSubmit' %>
  <% end %>
</div>

app/views/university/activate.html.erb
<div>
  University name: <%= @uni.name %><br>
  University weblink: <%= @uni.weblink %><br>
  University focal contact: <%= @uni.focal_contact %><br>
  University Remark: <%= @uni.remark %><br>

  <span class="alignCenter">
    <%= form_for Wallet.new, url: {controller: :paypals, action: :start_payment, method: :post} do |f| %>
      <%= label_tag(:amount, "Amount:", class: 'labelLarge') %>
      <%= f.text_field :amount, class: 'largeInput' %><br><br>

      <%= label_tag(:start_date, "Start Date:", class: 'labelLarge') %>
      <%= f.date_select :start_date, class: 'largeInput', autocomplete: "off"%><br>

      <%= label_tag(:end_date, "End Date:", class: 'labelLarge') %>
      <%= f.date_select :end_date, class: 'largeInput', autocomplete: "off"%><br>

      <%= label_tag(:submit, "", class: 'labelLarge') %>
      <%= f.submit 'Login', class: 'mediumSubmit' %>
      <% end %>
  </span>
  </div>
</div>

app/views/university/add_criteria.html.erb
<div class="col-lg-4">
  <%= label_tag :space, "" %>
</div>

<div class="col-lg-8">
  <%= render(partial: "users/profiles/uni_admin_selection_criteria_nav", locals: {tabName: params[:type]
    .keys.first+"_tab"}) %>
</div>

app/views/university/application.html.erb
<script>
  document.getElementById('uni_sixth').classList.add("active");
</script>

<div class="col-lg-2">
  <%= label_tag :space, "" %>
</div>

<div class="col-lg-10">
  <%= form_for(current_user.university, url: filter_student_university_path(current_user.university)) do |f| %>
    <%= label_tag(:filter, "Filter Course", class: 'labelLarge') %>
    <%= f.select_tag :criteria, options_for_select([["PHD", "phd"], ["Post Graduate", "post_graduate"], ["Under
    Graduate", "graduate"], ["Diploma", "diploma"], ["Certificate Or High School", "high_school"]], params[:criteria]), class:
      'borderlessInputLarge' %>
    <%= f.submit 'Search', class: 'mediumSubmit' %>
  <% end %><br><br><br>

  <table class="table", style="width: 100%;">
    <tr style="height: 50px; background-color: #ddd;">
      <th>Course Name</th><th>Total Fees</th><th>Total Application</th>
    </tr>
    <% @courses.each do |c| %>
      <tr>
        <th><%= c.name %></th>
        <td><%= c.total_fees %></td>
        <td><a style="color: dodgerblue;" href="<%= root_url %>application_progress?course_id=<%= c.id %>"><%= c.application_progresses.count
        %></td>
      </tr>
    <% end %>
  </table>

  <div style="width: 100px;">
    <%= will_paginate @courses %>
  </div>

</div>

app/views/university/create.html.erb
<span class="col-lg-3">
  <%= label_tag nil %>
</span>

<div class="col-lg-9">
  <div class="line">
    Activate account if you have registered
  </div><br><br><br><br><br>

  <div>
    <%= form_tag(root_url+"/university/search", method: :get) do %>
      <%= label_tag(:token, "Token:", class: "labelLarge") %>
      <%= text_field_tag :token, params[:token], class: 'largeInput' %>
      <%= submit_tag('search', class: "mediumSubmit") %>
    <% end %>
  </div><br><br>

  <div class="col-lg-9">
    <div class="line">
      Register University
    </div><br><br><br><br><br>

    <%= form_for @uni, url: {action: :update, method: :put, id: @uni.id} do |f| %>
      <%= label_tag(:uni_name, "University Name:", class: 'labelLarge') %>
      <%= f.text_field :name, class: 'largeInput' %><br><br>

      <%= label_tag(:weblink, "Website Link:", class: 'labelLarge') %>
      <%= f.text_field :weblink, class: 'largeInput' %><br><br>

      <%= label_tag(:campus, "Campus:", class: 'labelLarge') %>
      <%= f.text_field :campus, class: 'largeInput' %><br><br>

      <%= label_tag(:remark, "Remark:", class: 'labelLarge') %>
      <%= f.text_area :remark, class: 'extraLargeInput' %><br><br>

      <div class="line">
        Focal Contact
      </div><br><br><br><br><br>

      <%= f.fields_for :focal_contact do |g| %>
        <%= label_tag(:firstname, "First Name:", class: 'labelLarge') %>
        <%= g.text_field :firstname, class: 'largeInput' %><br><br>

        <%= label_tag(:middlename, "Middle Name:", class: 'labelLarge') %>
        <%= g.text_field :middlename, class: 'largeInput' %><br><br>

        <%= label_tag(:lastname, "Last Name:", class: 'labelLarge') %>
        <%= g.text_field :lastname, class: 'largeInput' %><br><br>

        <%= label_tag(:email, "Email:", class: 'labelLarge') %>
        <%= g.text_field :email, class: 'largeInput' %><br><br>

        <%= label_tag(:phone_no, "Phone No:", class: 'labelLarge') %>
        <%= g.text_field :phone_number, class: 'largeInput' %><br><br>
      <% end %>

      <div class="line">
        University Address
      </div><br><br><br><br><br>

      <%= f.fields_for :address do |g| %>
        <%= label_tag(:street_no, "Street No:", class: 'labelLarge') %>
        <%= g.text_field :street_no, class: 'smallInput' %><br><br>

        <%= label_tag(:street_name, "Street Name:", class: 'labelLarge') %>
        <%= g.text_field :street_name, class: 'mediumInput' %><br><br>

        <%= label_tag(:suburb, "Suburb:", class: 'labelLarge') %>
        <%= g.text_field :suburb, class: 'mediumInput' %><br><br>

        <%= label_tag(:post_code, "Post Code:", class: 'labelLarge') %>
        <%= g.text_field :post_code, class: 'smallInput' %><br><br>

        <%= label_tag(:city, "City:", class: 'labelLarge') %>
        <%= g.text_field :city, class: 'mediumInput' %><br>

        <%= label_tag(:country, "Country:", class: 'labelLarge') %>
        <%= g.text_field :country, class: 'mediumInput' %><br><br>
      <% end %>


      <%= label_tag(:submit, "", class: 'labelLarge') %>
      <%= f.submit 'Update Account', class: 'largeSubmit' %><br><br>
    <% end %>
  </div>
</div>

app/views/university/filter_student.html.erb
<script>
  document.getElementById('uni_fifth').classList.add("active");
</script>

<div class="col-lg-2">
  <%= label_tag :space, "" %>
</div>

<div class="col-lg-10">
  <%= form_for(current_user.university, url: filter_student_university_path(current_user.university)) do |f| %>
    <%= label_tag(:filter, "Filter Course", class: 'labelLarge') %>
    <%= f.select_tag :criteria, options_for_select([["PHD", "phd"], ["Post Graduate", "post_graduate"], ["Under
    Graduate", "graduate"], ["Diploma", "diploma"], ["Certificate Or High School", "high_school"]], params[:criteria]), class:
      'borderlessInputLarge' %>
    <%= f.submit 'Search', class: 'mediumSubmit' %>
  <% end %><br><br><br>

  <table class="table", style="width: 100%;">
    <tr style="height: 50px; background-color: #ddd;">
      <th>Student Name</th><th>Email</th><th>Country
    </th><th>Academic Score</th><th>English Competency</th><th>Total Experience</th><th>Ation</th>
    </tr>
    <% @students.each do |g| %>
      <tr>
        <th><%= g.name %></th>
        <td><%= g.email %></td>
        <td><%= g.country %></td>
        <td><%= g.highest_qualification_name %></td>
        <td><%= g.highest_english_competency_name %></td>
        <td><%= g.total_experience %></td>
        <td><a style="color: dodgerblue;" href="<%= root_url %>users/student_details?student_id=<%= g.id %>">View</a></td>
      </tr>
    <% end%>
  </table>
<!--  <div style="width: 100%; height: 30px; background-color: lightgrey;">-->
    <%#= will_paginate @students %>
<!--  </div>-->

</div>

app/views/university/new.html.erb
<div style="padding-top: 200px; padding-left: 300px; padding-bottom: 20px;">
  <div class="line" style="line-height: 1.6; font-size: 16px;">
    <p>Register your university and instantly start receiving prospective student's application from
    across the globe. Once you register your university,<br>you will receive an approval token from admin in
      your email with authorization to go ahead and setup your profile.
    <a href="<%= root_url %>university/search">Activate your account if you<br> receive your token after
      registration</a></p>
  </div>

  <div class="subject_title">
    University Registration Form
  </div>

  <%= form_for @uni, validate: true, url: {action: :create, method: :post} do |f| %>
    <%= label_tag(:uni_name, "University Name:", class: 'labelExtraLarge') %>
    <%= f.text_field :name, class: 'borderlessInputLarge' %>

    <%= label_tag(:campus, "Campus:", class: 'labelLarge') %>
    <%= f.text_field :campus, class: 'borderlessInputMedium' %><br><br>

    <%= label_tag(:weblink, "Website Link:", class: 'labelExtraLarge') %>
    <%= f.text_field :weblink, class: 'borderlessInputLarge' %><br><br>


    <%= label_tag(:remark, "Remark:", class: 'labelExtraLarge') %>
    <%= f.text_area :remark, class: 'texareaMediumInput' %><br><br>
    <div class="subject_title">
      Focal Contact
    </div>

    <%= f.fields_for :focal_contact do |g| %>
      <%= label_tag(:firstname, "First Name:", class: 'labelLarge') %>
      <%= g.text_field :firstname, class: 'borderlessInputMedium' %>

      <%= label_tag(:middlename, "Middle Name:", class: 'labelLarge') %>
      <%= g.text_field :middlename, class: 'borderlessInputMedium' %>

      <%= label_tag(:lastname, "Last Name:", class: 'labelLarge') %>
      <%= g.text_field :lastname, class: 'borderlessInputMedium' %><br><br>

      <%= label_tag(:phone_no, "Phone No:", class: 'labelLarge') %>
      <%= g.text_field :phone_number, class: 'borderlessInputMedium' %>

      <%= label_tag(:email, "Email:", class: 'labelLarge') %>
      <%= g.text_field :email, class: 'borderlessInputLarge' %>


    <% end %>

    <div class="subject_title">
      University Address
    </div>

    <%= f.fields_for :address do |g| %>
      <%= label_tag(:street_no, "Street No:", class: 'labelLarge') %>
      <%= g.text_field :street_no, class: 'borderlessInputMedium' %>

      <%= label_tag(:street_name, "Street Name:", class: 'labelLarge') %>
      <%= g.text_field :street_name, class: 'borderlessInputMedium' %>

      <%= label_tag(:suburb, "Suburb:", class: 'labelLarge') %>
      <%= g.text_field :suburb, class: 'borderlessInputMedium' %><br><br>

      <%= label_tag(:post_code, "Post Code:", class: 'labelLarge') %>
      <%= g.text_field :post_code, class: 'borderlessInputMedium' %>

      <%= label_tag(:city, "City:", class: 'labelLarge') %>
      <%= g.text_field :city, class: 'borderlessInputMedium' %>

      <%= label_tag(:country, "Country:", class: 'labelLarge') %>
      <%= g.text_field :country, class: 'borderlessInputMedium' %><br><br>
    <% end %>

    <span style="padding-left: 100px;">
      <%= label_tag(:submit, "", class: 'labelLarge') %>
      <%= f.submit 'Create Account', class: 'largeSubmit' %>
    </span>
  <% end %>
</div>

<script>
  document.getElementById("first_tab").classList.add("active");
  document.getElementById("sub_label").value = "Register yourself university and start accepting applications from " +
    "prospective students";
</script>

app/views/university/prospective_student.html.erb
<script>
  document.getElementById('uni_fifth').classList.add("active");
</script>

<div class="col-lg-2">
  <%= label_tag :space, "" %>
</div>

<div class="col-lg-10">
  <%= form_for(current_user.university, url: filter_student_university_path(current_user.university)) do |f| %>
    <%= label_tag(:filter, "Filter Course", class: 'labelLarge') %>
    <%= f.select_tag :criteria, options_for_select([["PHD", "phd"], ["Post Graduate", "post_graduate"], ["Under
    Graduate", "graduate"], ["Diploma", "diploma"], ["Certificate Or High School", "high_school"]]), class: 'borderlessInputLarge' %>
    <%= f.submit 'Search', class: 'mediumSubmit' %>
  <% end %><br><br><br>

  <table class="table", style="width: 100%;">
    <tr style="height: 50px; background-color: #ddd;">
      <th>Student Name</th><th>Email</th><th>Country
    </th><th>Academic Score</th><th>English Competency</th><th>Total Experience</th><th>Ation</th>
    </tr>
    <% @students.each do |g| %>
      <tr>
        <th><%= g.name %></th>
        <td><%= g.email %></td>
        <td><%= g.country %></td>
        <td><%= g.highest_qualification_name %></td>
        <td><%= g.highest_english_competency_name %></td>
        <td><%= g.total_experience %></td>
        <td><a style="color: dodgerblue;" href="<%= root_url %>users/student_details?student_id=<%= g.id %>">View</a></td>
      </tr>
    <% end%>
  </table>
  <div style="width: 50px;">
    <%= paginate @students if @students.present? %>
  </div>
</div>

app/views/university/reload.html.erb
<div class="col-lg-4">
  <%= label_tag :space, "" %>
</div>

<div class="col-lg-8">
  <%= render(partial: "users/profiles/uni_admin_selection_criteria_nav", locals: {tabName: params[:type]+"_tab"}) %>
</div>

app/views/university/show.html.erb
<div class="col-lg-3">
  <%= label_tag nil %>
</div>

<div class="col-lg-9">
  <% if params[:type].eql? "criteria" %>
    <%= render(partial: "university/criteria") %>
  <% else %>
    <%= render(partial: "university/university_profile") %>
  <% end %>
</div>