config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    passwords: 'passwords',
    registrations: 'registrations',
    invitations: 'invitations',
    sessions: 'sessions'
  }

  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # mount ActionCable.server => '/cable'

  resources :university do
    resources :faculty
    collection do
      get :valid_token
      get :search
    end

    member do
      get :prospective_student
      patch :filter_student
      get :application
    end

    member do
      patch :activate
      patch :add_criteria
      get :reload
    end
  end

  resources :course do
    member do
      get :detail
    end

    resources :unit do
      collection do
        get :course_units
        get :search
      end
    end
  end

  resources :application_progress do
    member do
      patch :transition
    end
  end


  resources :student do
    member do
      patch :add_academic
      get :reload
      get :recommendation
      get :application
      patch :filter_application
    end
  end

  resources :courses_unit, only: [:create, :destroy]
  resources :uni_admin
  resources :users_invitations do
    collection do
      get :valid_token
    end

    member do
      put :accept_invitation
    end
  end

  resources :search_engine do
    collection do
      get :search_unit
      get :item_detail
    end
  end


  resources :users do
    collection do
      get :students
      get :universities
      get :student_details
    end
    member do
      post :invite
    end
  end

  resource :subjects
  resources :chats do
    collection do
      get :application
    end
  end

  mount ActionCable.server => '/cable'

  resources :paypals do
    collection do
      post :start_payment
      get :verify_payment
    end
  end

  get 'paypal_confirm', to: 'paypals#verify_payment'

end

app/models/course.rb
require 'elasticsearch/model'
class Course < ActiveRecord::Base
  include CourseFilter
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  validates_presence_of :name, :code, :duration, :rank
  belongs_to :faculty, inverse_of: :courses
  belongs_to :course_category, inverse_of: :courses
  has_many :course_units, inverse_of: :course, dependent: :destroy
  has_many :units, through: :course_units
  has_many :application_progresses, inverse_of: :course, dependent: :destroy
  has_many :english_competencies, as: :competenciable, dependent: :destroy
  has_many :academic_eligibilities, as: :eligiable, dependent: :destroy
  has_many :subjects, as: :subjectable, class_name: 'Subject', dependent: :destroy
  accepts_nested_attributes_for :english_competencies, allow_destroy: true
  accepts_nested_attributes_for :academic_eligibilities, allow_destroy: true

  enum rank: {high_school: 0, diploma: 1, graduate: 2, post_graduate: 3, phd: 4}
  enum semester_type: {semester: 0, tri_semester: 1}

  delegate :university_name, to: :faculty, prefix: false, allow_nil: :false

  # after_save    { Indexer.perform_async(:index,  self.id) }
  # after_destroy { Indexer.perform_async(:delete, self.id) }

  settings do
    mappings dynamic: false do
      indexes :code, type: :text
      indexes :name, type: :text
    end
  end

  def search_detail
    "#{name} is offered in #{university_name} and has #{units.count} units.
      For details you can visit this link..."
  end

  def course_name
    "#{name} at #{university_name}"
  end

  def as_indexed_json(options={})
    self.as_json(
      include: {
        units:  { methods: [:code_name], only: [:code_name] }
      })
  end

  def english_competencies
    super
    # super.present? ? super : super.build(competency_attributes)
  end

  def academic_eligibilities
    super
    # super.present? ? super : super.build(academic_attributes)
  end

  def competency_attributes
    faculty.university.english_competencies.map {|eng|
      {
        overall_band: eng.overall_band,
        competency_type: eng.competency_type,
        speaking: eng.speaking,
        listening: eng.listening,
        writing: eng.writing,
        reading: eng.writing
      }
    }
  end

  def academic_attributes
    faculty.university.academic_eligibilities.map {|aca|
      {code: aca.code, eligibility_type: aca.eligibility_type, minimum_score: aca.minimum_score}
    }
  end

end

app/controllers/course_controller.rb
class CourseController < ApplicationController

  def create
    @course = Course.new(course_params)
    @course.course_category_id = params[:course_category_id]
    @course.rank = params[:rank]

    if @course.save
      redirect_to(action: :index, params: {faculty_id: params[:course][:faculty_id]})
    else
      render json: {error: {message: 'Error creating Course'}, success: false}, status: :unprocessable_entity
    end
  end

  def show
    @course = Course.find(params[:id])
    @course_categories = CourseCategory.all
  end

  def update
    @course = Course.find(params[:id])
    form = CourseUpdateForm.new(@course, params)
    if form.update
      flash[:success] = 'Course details updated successfully'
    else
      flash[:danger] = 'Course details failed to update'
    end
    redirect_to(action: :show, params: {id: @course.id})
  end

  def new
    @faculty = find_faculty
    @course = Course.new(faculty_id: @faculty.id)
    @course_categories = CourseCategory.all
  end

  def search
    @course = Course.find_by(code: params[:search])
  end

  def index
    @faculty = find_faculty
    @courses = @faculty.courses.page(params[:page])
  end

  def destroy
    @course = Course.find(params[:id])
    if @course.destroy
      redirect_to(action: :index, params: {faculty_id: @course.faculty_id})
    else
      render json: {error: {message: 'Error Deleting Faculty'}, success: false}, status: :unprocessable_entity
    end
  end

  def detail
    @course = Course.find(params[:id])
  end

  private

  def find_faculty
    Faculty.find(params[:faculty_id])
  end

  def course_params
    params.require(:course).permit(:name, :code, :duration, :semester_type, :rank, :faculty_id, :total_fees,
      :course_category_id,
      english_competencies_attributes: [:id, :overall_band, :expiry, :competency_type, :speaking, :listening, :writing,
        :reading],
      academic_eligibilities_attributes: [:id, :code, :eligibility_type, :minimum_score])
      .merge!(semester_type: params[:semester_type])
  end

end

app/views/course/_course_criteria.html.erb
<script>
  document.getElementById('uni_fourth').classList.add("active");
</script>

<h1>Academic Scores:</h1>

<div class="tab">
  <button class="tablinks" id="course_tab" onclick="openAcademic(event, 'course')">Course Detail</button>
  <button class="tablinks" id="english_tab" onclick="openAcademic(event, 'english')">English Competency</button>
  <button class="tablinks" id="subject_tab" onclick="openAcademic(event, 'subject')">Prerequisite Subjects</button>
</div>

<div id="course" class="tabcontent">
  <%= render(partial: "course/course_detail") %>
</div>

<div id="english" class="tabcontent">
  <%= render(partial: "course/english") %>
</div>

<div id="subject" class="tabcontent">
  <%= render(partial: "course/subject") %>
</div>

<div>
  <script>
    function openAcademic(evt, academicName) {
      var i, tabcontent, tablinks;
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
      }
      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
      }
      document.getElementById(academicName).style.display = "block";
      evt.currentTarget.className += " active";
    }

    var tabsName = "<%= tabName %>" != null ? "<%= tabName %>" : "course_tab";
    document.getElementById(tabsName).click();
  </script>
</div>

app/views/course/_course_detail.html.erb
<div style="padding-bottom: 50px; padding-top: 25px;">
  <span style="color: darkorange; font-size: 20px;">Update Course Update</span>
</div>

<div>
  <%= form_for @course, url: {action: :update, method: :put} do |f| %>
    <%= hidden_field(:type, value='course') %>
    <%= label_tag(:name, "Course Code:", class: 'labelExtraLarge') %>
    <%= f.text_field :code, class: 'borderlessInputMedium' %><br><br>

    <%= label_tag(:name, "Course Name:", class: 'labelExtraLarge') %>
    <%= f.text_field :name, class: 'borderlessInputLarge' %><br><br>

    <%= label_tag(:semester_type, "Session Type:", class: 'labelExtraLarge') %>
    <%= f.select_tag(:semester_type, options_for_select([["Semester", "semester"], ["Trimester", "tri_mester"]],
        @course.semester_type), class: 'borderlessInputLarge')
    %><br><br>

    <%= label_tag(:duration, "Total Sessions:", class: 'labelExtraLarge') %>
    <%= f.number_field :duration, class: 'borderlessInputMedium' %><br><br>

    <%= label_tag(:total_fees, "Total Fees:", class: 'labelExtraLarge') %>
    <%= f.text_field :total_fees, class: 'borderlessInputMedium' %><br><br>

    <%= label_tag(:course_category, "Category:", class: 'labelExtraLarge') %>
    <%= select_tag(:course_category_id, options_from_collection_for_select(@course_categories, "id", "name", @course
      .course_category_id), class:
      'borderlessInputLarge') %><br><br>

    <%= label_tag(:rank, "Rank:", class: 'labelExtraLarge') %>
    <%= f.select_tag(:rank, options_for_select([["Certificate Or High School", "high_school"], ["Diploma", "diploma"],
      ["Under Graduate", "graduate"], ["Post Graduate", "post_graduate"], ["PHD", "phd"]], @course.rank), class: 'borderlessInputLarge')
    %><br><br>

    <%= label_tag(:submit, "", class: 'labelLarge') %>
    <%= f.submit 'Update', class: 'mediumSubmit' %>
  <% end %>
</div>

app/views/course/_english.html.erb
<div style="padding-bottom: 50px; padding-top: 25px;">
  <span style="color: darkorange; font-size: 20px;">Update English Competency</span>
</div>

<div>
  <%= form_for @course, url: {action: :update, method: :put} do |f| %>
    <%= f.fields_for :english_competencies_attributes do |g| %>
      <%= hidden_field(:type, value='english') %>
      <%= label_tag(:competency_type, "Type:", class: 'labelLarge') %>
      <%= select_tag(:competency_type, options_for_select(["IELTS", "PTE" ], "IELTS"), class: 'borderlessInputMedium') %>

      <%= label_tag(:overall_band, "Overall Band:", class: 'labelLarge') %>
      <%= g.number_field :overall_band,  step: :any, class: 'borderlessInputMedium' %>
      <%= label_tag(:speaking, "Speaking:", class: 'labelLarge') %>
      <%= g.number_field :speaking, step: :any, class: 'borderlessInputMedium' %><br>

      <%= label_tag(:writing, "Writing:", class: 'labelLarge') %>
      <%= g.number_field :writing, step: :any, class: 'borderlessInputMedium' %>

      <%= label_tag(:reading, "Reading:", class: 'labelLarge') %>
      <%= g.number_field :reading, step: :any, class: 'borderlessInputMedium' %>

      <%= label_tag(:listening, "Listening:", class: 'labelLarge') %>
      <%= g.number_field :listening, step: :any, class: 'borderlessInputMedium' %><br>
      <%= label_tag(:submit, "", class: 'labelLarge') %>
      <%= f.submit 'Add', class: 'mediumSubmit' %><br><br>
    <% end %>
  <% end %><br><br>


  <table class="table", style="width: 100%;">
    <tr style="height: 50px; background-color: #ddd;">
      <th>Type</th><th>Expiry</th><th>Overall
      Bank</th><th>Speaking</th><th>Writing</th><th>Reading</th><th>Listening</th><th>Action</th>
    </tr>
    <% @course.english_competencies.select(&:persisted?).each do |g| %>
      <tr>
        <th><%= g.competency_type %></th>
        <td><%= g.expiry %></td>
        <td><%= g.overall_band %></td>
        <td><%= g.speaking %></td>
        <td><%= g.writing %></td>
        <td><%= g.reading %></td>
        <td><%= g.listening %></td>
        <td><a style="color: red;" href="<%= root_url %>university/<%= current_user.university_id
        %>/reload?destroy=true&type=english&type_id=<%= g.id %>&course_id=<%= @course.id %>">delete</a></td>
      </tr>
    <% end%>
  </table>
</div>

app/views/course/_subject.html.erb
<%= form_for @course, url: {action: :update, method: :put} do |f| %>
  <%= f.fields_for :subjects_attributes do |g| %>
    <br><br>
    <%= hidden_field(:type, value='subject') %>
    <%= label_tag(:name, "Subject Name:", class: 'labelLarge') %>
    <%= g.text_field :name, class: 'borderlessInputLarge' %><br><br>

    <%= label_tag(:percentage, "Score:", class: 'labelLarge') %>
    <%= g.number_field :percentage, step: :any, class: 'borderlessInputMedium' %><br><br>

    <%= label_tag(:description, "Description:", class: 'labelLarge') %>
    <%= g.text_area :description, class: 'extraLargeInput' %><br><br>

    <%= label_tag(:submit, "", class: 'labelLarge') %>
    <%= f.submit 'Add', class: 'mediumSubmit' %><br><br>
  <% end %>
<% end %><br><br>

<table class="table", style="width: 100%;">
  <tr style="height: 50px; background-color: #ddd;">
    <th>Name</th><th>Score</th><th>Description</th><th>Action</th>
  </tr>
  <% @course.subjects.select(&:persisted?).each do |g| %>
    <tr>
      <th><%= g.name %></th>
      <td><%= g.percentage %></td>
      <td><%= g.description %></td>
      <td><a style="color: red;" href="<%= root_url %>/university/<%= current_user.university_id
      %>/reload?destroy=true&type=subject&type_id=<%= g.id %>&course_id=<%= @course.id %>">delete</a></td>
    </tr>
  <% end%>
</table>

app/views/course/detail.html.erb
<script>
  document.getElementById('stud_fourth').classList.add("active");
</script>

<div class="col-lg-4">
  <%= label_tag :space, "" %>
</div>

<div class="col-lg-8">
  <p style="color: darkorange; font-size: 20px;">Course Details</p><br>
  <b style="font-size: 16px;">Course Code:</b> <%= @course.code %><br><br>
  <b style="font-size: 16px;">Course Name:</b> <%= @course.name %><br><br>
  <b style="font-size: 16px;">Duration:</b> <%= @course.duration %> Semesters<br><br>
  <b style="font-size: 16px;">Total Fees:</b> <%= @course.total_fees %><br><br>
  <b style="font-size: 16px;">Course Level:</b> <%= CONSTANTS[@course.rank_before_type_cast]%>

  <p style="color: darkorange; font-size: 20px; padding-top: 50px;">Unit Details</p><br>
  <table class="table", style="width: 100%;">
    <tr style="height: 50px; background-color: #ddd;">
      <th width="300", height="40">Name</th>
      <th width="200", height="40">Code</th>
      <th width="200">Credit Point</th>
      <th width="200">Level</th>
    </tr>
    <% @course.units.each do |cor_unit| %>
      <tr>
        <td height="40">
          <%= cor_unit.code %>
        </td>

        <td height="40">
          <%= cor_unit.name %>
        </td>

        <td height="40">
          <%= cor_unit.credit_point %>
        </td>

        <td height="40">
          <%= cor_unit.level %>
        </td>
      </tr>
    <%end%>

  </table>


  <p style="color: darkorange; font-size: 20px; padding-top: 50px;">Application Submission</p><br>
  <%= form_for ApplicationProgress.new, url: {controller: :application_progress, action: :create, method: :post} do |f| %>
    <%= f.hidden_field :course_id, value: @course.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.fields_for :attachables_attributes do |g| %>
      <%= g.hidden_field(:name, value: 'Application File') %>
      <%= g.label_tag(:file, "Application Form/Cover Letter") %><br>
      <%= g.file_field(:file)%><br><br>
    <% end %>

    <%= f.submit 'Apply', class: 'mediumSubmit' %>
  <%end %>
</div>

app/views/course/index.html.erb
<script>
  document.getElementById('uni_fourth').classList.add("active");
</script>

<div class="col-lg-2">
  <%= label_tag nil %>
</div>

<div class="col-lg-10">
  <div style="padding-top: 50px;">
    <span style="color: darkorange; font-size: 20px;"> Course Details </span>
    <span style="color: blue; font-size: 20px; padding-left: 80%">
      <a style="color: dodgerblue" href="<%= root_url %>course/new?faculty_id=<%= @faculty.id %>">Add Course</a>
    </span>
  </div>
  <table class="table", style="width: 100%;">
    <tr style="height: 50px; background-color: #ddd;">
      <th width="300", height="40">Name</th>
      <th width="200", height="40">Code</th>
      <th width="200">Duration</th>
      <th width="200">Rank</th>
      <th width="200">Unit Count</th>
      <th width="200">Action</th>
    </tr>
    <% @courses.each do |course| %>
      <tr>
        <td height="40">
          <%= course.name %>
        </td>

        <td height="40">
          <%= course.code %>
        </td>

        <td height="40">
          <%= course.duration %> semester
        </td>

        <td height="40">
          <%= course.rank %>
        </td>

        <td height="40">
          <%= link_to course.course_units.count, course_units_course_unit_index_path(course_id: course.id), method:
            :get, :style=> "color: blue;" %>
        </td>

        <td height="40">
          <a style="color: blue;" href="<%= root_url %>course/<%= course.id %>">Edit</a>
          ||
          <%= link_to "Delete", course_path(id: course.id), method: :delete, :style=> "color: red;", data: {
            confirm: 'Are you sure?'
          }%>
        </td>
      </tr>
    <%end%>

  </table>
  <div style="width: 50px;">
    <%= paginate @courses %>
  </div>
</div>

app/views/course/new.html.erb
<div class="col-lg-3">
  <%= label_tag nil %>
</div>

<div class="col-lg-9">
  <h1>Course Creation</h1><br>

  <%= form_for @course, url: {action: :create, method: :post} do |f| %>
    <%= f.hidden_field :faculty_id, value: @faculty.id %><br><br>
    <%= label_tag(:name, "Course Code:", class: 'labelLarge') %>
    <%= f.text_field :code, class: 'borderlessInputMedium' %><br><br>

    <%= label_tag(:name, "Course Name:", class: 'labelLarge') %>
    <%= f.text_field :name, class: 'borderlessInputMedium' %><br><br>

    <%= label_tag(:duration, "Total Semester:", class: 'labelLarge') %>
    <%= f.text_field :duration, class: 'borderlessInputMedium' %><br><br>

    <%= label_tag(:total_fees, "Total Fees:", class: 'labelLarge') %>
    <%= f.text_field :total_fees, class: 'borderlessInputMedium' %><br><br>

    <%= label_tag(:course_category, "Category:", class: 'labelLarge') %>
    <%= select_tag(:course_category_id, options_from_collection_for_select(@course_categories, "id", "name"), class:
        'borderlessInputMedium') %><br><br>

    <%= label_tag(:rank, "Rank:", class: 'labelLarge') %>
    <%= f.select_tag(:rank, options_for_select([["Certificate Or High School", "high_school"], ["Diploma", "diploma"],
      ["Under Graduate", "graduate"], ["Post Graduate", "post_graduate"], ["PHD", "phd"]]), class: 'borderlessInputMedium')
    %><br><br>

    <%= label_tag(:submit, "", class: 'labelLarge') %>
    <%= f.submit 'Create', class: 'mediumSubmit' %>
  <% end %>

<!--    <div class="line">-->
<!--      English Competency-->
<!--    </div><br><br><br><br><br>-->

    <%#= render(partial: "course/course_criteria", locals: {tabName: 'english_tab'}) %>

    <%#= f.fields_for :english_competencies do |g| %>
      <%#= label_tag(:competency_type, "Type:", class: 'labelLarge') %>
<!--      <%#= g.text_field :competency_type, class: 'smallInput', readonly: "readonly" %><br><br>-->

      <%#= label_tag(:overall_band, "Overall Band:", class: 'labelLarge') %>
<!--      <%#= g.text_field :overall_band, class: 'smallInput' %><br><br>-->

      <%#= label_tag(:speaking, "Speaking:", class: 'labelLarge') %>
      <%#= g.text_field :speaking, class: 'smallInput' %>

      <%#= label_tag(:writing, "Writing:", class: 'labelLarge') %>
<!--      <%#= g.text_field :writing, class: 'smallInput' %><br><br>-->

      <%#= label_tag(:reading, "Reading:", class: 'labelLarge') %>
      <%#= g.text_field :reading, class: 'smallInput' %>

      <%#= label_tag(:listening, "Listening:", class: 'labelLarge') %>
<!--      <%#= g.text_field :listening, class: 'smallInput' %><br><br><br><br>-->
<!--    <%# end %><br><br>-->

<!--    <div class="line">-->
<!--      Academic Eligibility-->
<!--    </div><br><br><br><br><br>-->

    <%#= f.fields_for :academic_eligibilities do |g| %>
<!--      <%#= g.hidden_field :code, class: 'smallInput' %><br><br>-->

      <%#= label_tag(:eligibility_type, "Qualification:", class: 'labelLarge') %>
      <%#= g.text_field :eligibility_type, class: 'largeInput', readonly: "readonly" %>

      <%#= label_tag(:minimum_score, "Minimum Score:", class: 'labelLarge') %>
<!--      <%#= g.text_field :minimum_score, class: 'smallInput' %><br><br>-->
    <%# end %>


</div>

app/views/course/show.html.erb
<div class="col-lg-3">
  <%= label_tag nil %>
</div>

<div class="col-lg-9">
  <%= render(partial: "course/course_criteria", locals: {tabName: 'course_tab'}) %>
</div>